name = "groups-webhooks-coda"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[env.production]
name = "planning-center-groups-webhook-prod"

[env.staging]
name = "planning-center-groups-webhook-staging"

# Environment variables (set these via wrangler secret)
# wrangler secret put WEBHOOK_SECRET
# wrangler secret put CODA_API_TOKEN
# 
# Set these as plain text vars or secrets:
[vars]
CODA_DOC_ID = "dNKK06PRQBP"
CODA_TABLE_ID = "tut8-Cju"

# KV Namespaces (if needed for storing webhook data)
# [[kv_namespaces]]
# binding = "WEBHOOKS_KV"
# id = "your-kv-namespace-id"

# Durable Objects (if needed for stateful processing)
# [[durable_objects.bindings]]
# name = "WEBHOOK_PROCESSOR"
# class_name = "WebhookProcessor"

# Rate limiting
# [[unsafe.bindings]]
# name = "RATE_LIMITER"
# type = "ratelimit"
# namespace_id = "1"
# simple = { limit = 100, period = 60 }